### ISSUE TITLE
support for spatial lines

### ISSUE THREAD

**Issue by gillesgerlo** [r-spatial/leafgl#1]
Great package, any way to also use the functionality to plot spatial lines?

**Comment by tim-salabim** [comment]
Thanks! 
As I said on [twitter](https://twitter.com/TimSalabim3/status/1044575333519953921) I'd love to implement support for lines, however, the upstream dependency at https://github.com/robertleeplummerjr/Leaflet.glify does currently not support lines, so there is little I can do on my end. 

I suggest you open a feature request for lines there and link back to this one to show where it originated. Once lines support is available in Leaflet.glify, I am more than happy to implement it here.

**Comment by gillesgerlo** [comment]
Oh sorry I did actually have a look at their github, but missed that the lines functionality is set as planned ;)

Will have a look!

**Comment by tim-salabim** [comment]
Great news. The upstream dependency has just implemented line support. I will integrate this here asap.

**Comment by wimpel** [comment]
That is indeed great news Tim! If I can help testing (not very good at coding yet), let me know.

**Comment by tim-salabim** [comment]
This commit adds support for lines. Testing welcome!

**Comment by tim-salabim** [comment]
Closing here as lines are well supported now
