### ISSUE TITLE
leafgl vs deckgl vs mapdeck

### ISSUE THREAD

**Issue by harryprince** [r-spatial/leafgl#11]
it seems leaflet GL solution is not popular than [deckgl](https://github.com/crazycapivara/deckgl) or [mapdeck](https://github.com/SymbolixAU/mapdeck) which base on uber deck.gl framework, and I am a new bee with large-scale point viz.

Do anyone know why we need these frameworks which looks like an overlay with each other, what is the difference between them?

**Comment by tim-salabim** [comment]
I cannot comment on a comparison between deckgl and mapdeck. The difference between those two and leafgl is that leafgl is fully leaflet compatible, which the other two are not. 

May I ask why you consider such a comparison to be important? To me it is like asking what is the difference between lattice and ggplot2... which one could compare, but in the end they are simply two different ways of using grid to provide a high level plotting environment.

**Comment by tim-salabim** [comment]
Closing here due to lack of activity
