### ISSUE TITLE
Support for CRS.Simple

### ISSUE THREAD

**Issue by AB-Kent** [r-spatial/leafgl#13]
Would it be possible to support maps which are not in the standard projection? Specifically I would like to use `addGlPoints` with a map created using `L.CRS.Simple`. My base map is a microscope image of a tissue section; I would like to draw points representing hundreds of thousands of cells as a layer on top. It works (slowly) to use `leaflet::addCircles` with coordinates in the range 0-255; this fails with `leafgl::addGlPoints` because it tries to convert the points to EPSG:4326.

Example with no base map:
```
library(leaflet)
library(leafgl)
library(magrittr)

n=1000
pts = data.frame(id = 1:n,
                 x = rnorm(n, 128, 30),
                 y = rnorm(n, -128, 18))

crs <- leafletCRS(crsClass = "L.CRS.Simple")
map = leaflet(options = leafletOptions(crs = crs)) %>% 
  setView(128, -128, 1) 

# Works
map %>% addCircles(data=pts, lat=~y, lng=~x)

# Doesn't work
map %>% addGlPoints(st_as_sf(pts, coords=c('x', 'y')))

#Error in st_transform.sfc(st_geometry(x), crs, ...) : 
#  sfc object should have crs set
#Calls: %>% ... st_transform.sf -> st_transform -> st_transform.sfc

```

**Comment by AB-Kent** [comment]
The changes needed are small. There is one change needed in robertleeplummerjr/Leaflet.glify#29.

In this package, calls to `sf::st_transform(data, 4326)` need to be conditional on the CRS of the map:
```
if (map$x$options$crs$crsClass != 'L.CRS.Simple')
    data = sf::st_transform(data, 4326)
```

I have tried this in `addGlPoints` and (with the Leaflet.glify change) it fixes the example in my original post.

**Comment by AB-Kent** [comment]
The change proposed above only works if `map` is a `leaflet` object; if it is a `leaflet_proxy` then a different method is needed.

**Comment by tim-salabim** [comment]
@AB-Kent I've seen you've proposed a PR in the upstream repo. We should wait for it to be implemented there. I'll have a look at the leaflet_proxy issue once the upstream lib supports `L.CRS.Simple`

**Comment by AB-Kent** [comment]
Thanks! For the proxy, I think some way to query the browser is needed.

**Comment by AB-Kent** [comment]
The upstream pull request has been merged: https://github.com/robertleeplummerjr/Leaflet.glify/pull/33

Do you have any thoughts about how to determine the CRS of a `leaflet_proxy`?

Why I care: I work with microscope images stored in pyramidal TIFF format. Using leaflet and a tile server, the images can be displayed in a zoomable, pannable image. I'm using Shiny and leafgl to display hundreds of thousands of points, representing different cell types, on top of the microscope image. I'm planning to release this viewer as open source once the tile server is available.

Here is a short screencast showcasing the technology. leafgl  comes into use just after 2:00.
https://akoya.app.box.com/s/99ori44qxuz9r5j4sd520a7vj23lsg1l/file/538913743990

**Comment by tim-salabim** [comment]
Wow, this is an impressive app that you're showcasing there! Not that I have any clue what it does, but it is awesome to see how far a mapping engine can be stretched for different purposes!

In https://github.com/r-spatial/leafgl/commit/b92a8d829632d63ee42c7b9fe603b1d7a7c486d4 I've simply removed the on-the-fly-reprojection to 4326 (which should not happen anyways). This should be the easiest approach to achieve what you want as we don't need to infer the crs from the map from anywhere (assuming you control the map setup in the first place).

```r
library(leaflet)
library(leafgl)
library(mapview)
library(leafem)
library(sf)

m = leaflet::leaflet(
  options = leaflet::leafletOptions(
    minZoom = -1000,
    crs = leafletCRS(crsClass = "L.CRS.Simple")
  )
)

brew = st_transform(breweries, 3035)
fran = st_transform(st_cast(franconia, "POLYGON"), 3035)
trls = st_transform(st_cast(trails, "LINESTRING"), 3035)

m %>%
  addGlPoints(brew, popup = "founded") %>%
  addGlPolygons(fran) %>%
  addGlPolylines(trls) %>%
  setView(lng = 4389376, lat = 2964480, zoom = -9) %>%
  addMouseCoordinates()
```
now gives

![Screenshot from 2019-12-27 21-55-36](https://user-images.githubusercontent.com/2826432/71532452-ab0ad800-28f3-11ea-8223-8e77e23ecf5c.png)

The only thing that isn't working with `L.CRS.Simple` are lines. No idea why though... Maybe something in https://github.com/robertleeplummerjr/Leaflet.glify @robertleeplummerjr ?

**Comment by AB-Kent** [comment]
Yes that works brilliantly, thank you! I'm not using lines with `leafgl` at this time. The breakage there seems to be independent of this change.

**Comment by tim-salabim** [comment]
Good to hear that things work for you now.

**Comment by tim-salabim** [comment]
UPDATE: `L.CRS.Simple` now also working with lines.

The above code snippet now gives:

![Screenshot from 2020-01-19 10-37-03](https://user-images.githubusercontent.com/2826432/72678611-c22e8700-3aa7-11ea-98fd-709a65200f00.png)

I think we can close this here. Please re-open if you disagree.

**Comment by AB-Kent** [comment]
Nice, thank you!
