### ISSUE TITLE
Animation?

### ISSUE THREAD

**Issue by JimShady** [r-spatial/leafgl#14]
Hello,

Not an issue as such, more me thinking out loud, This (excellent) project could be used for animations?

For example I've got a few datasets of around 50,000 points at 1 minute resolution over a day. I'm struggling to create an animation/visualisation of them. Perhaps using the mapshot function in leaflet and this library I could quickly plot 24 x 60 PNG files and then stitch them together.

Cheers.

**Comment by tim-salabim** [comment]
Sorry for the late reply. I honestly wouldn't know without trying ...
