### ISSUE TITLE
popup parameter not working in `addGlPolygons`

### ISSUE THREAD

**Issue by statnmap** [r-spatial/leafgl#15]
Hi and thanks you for this useful package.  
Since the transfer from {leaflet.glify} to {leafgl}, the popup parameter does not work any more in `addGlPolygons`.

You can try with the example of the documentation. If I click on the polygons no popup appears. Same code with previous `addGlifyPolygons` is good:  
```r
library(mapview)
library(leaflet)
library(leafgl)
library(sf)
library(colourvalues)

fran = st_cast(franconia, "POLYGON")

cols = colour_values_rgb(fran$NUTS_ID, include_alpha = FALSE) / 255

options(viewer = NULL)

leaflet() %>%
  addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
  addGlPolygons(data = fran, color = cols, popup = "NAME_ASCI") %>%
  # leaflet.glify::addGlifyPolygons(data = fran, color = cols, popup = "NAME_ASCI") %>% 
  addMouseCoordinates() %>%
  setView(lng = 10.5, lat = 49.5, zoom = 8)
```

**Comment by tim-salabim** [comment]
I know, this seems to be an issue with the upstream repo though:
https://github.com/robertleeplummerjr/Leaflet.glify/issues/21

**Comment by phileas-condemine** [comment]
Hello @tim-salabim did the commit 9ee967d  on 13th of march in the leaflet.glify repo fix the issue ?
https://github.com/robertleeplummerjr/Leaflet.glify/issues/21
I am experiencing the same issue that @statnmap

**Comment by trafficonese** [comment]
The example works fine for me with the current version. So I guess it is fixed

**Comment by tim-salabim** [comment]
Yes, this should work again. NOTE though, that the default behaviour will likely change before CRAN release, as I found a way to display all attributes using js only, so will likely make this the default
