### ISSUE TITLE
JS canvasoverlay.js "module" and "require" not defined

### ISSUE THREAD

**Issue by fpirotti** [r-spatial/leafgl#21]
Hello and thanks for a great add-on to leaflet R. Using it on the first example in your page, points load fine, but adding a popup fails (no popups) with several JS errors that I list below. File aquare.glsl is aalso not found. Am I doing something wrong or is it an issue regaaarding versions?

canvasoverlay.js:142 Uncaught ReferenceError: module is not defined   at canvasoverlay.js:142
index.js:1 Uncaught ReferenceError: require is not defined    at index.js:1
map-matrix.js:1 Uncaught ReferenceError: module is not defined    at map-matrix.js:1
points.js:1 Uncaught ReferenceError: require is not defined    at points.js:1
shapes.js:2 Uncaught ReferenceError: require is not defined    at shapes.js:2
lines.js:2 Uncaught ReferenceError: require is not defined    at lines.js:2
utils.js:75 Uncaught ReferenceError: module is not defined    at utils.js:75
dot.glsl:1 Uncaught SyntaxError: Unexpected identifier (module.exports function not working)
point.glsl:1 Uncaught SyntaxError: Unexpected identifier (module.exports function not working)
polygon.glsl:1 Uncaught SyntaxError: Unexpected identifier (module.exports function not working)
puck.glsl:1 Uncaught SyntaxError: Unexpected identifier (module.exports function not working)
simple-circle.glsl:1 Uncaught SyntaxError: Unexpected identifier (module.exports function not working)
aquare.glsl:1 Failed to load resource: the server responded with a status of 404 (Not Found)
default.glsl:1 Uncaught SyntaxError: Unexpected identifier

**Comment by tim-salabim** [comment]
Hi, these errors also happen without adding a popup column. All these errors stem from the underlying js lib but don't seem to cause any issues (AFAICT). 

Regarding popups, how do you create them?

```r
m = leaflet() %>%
        addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
        addGlPoints(data = pts, group = "pts", popup = "id") %>%
        addMouseCoordinates() %>%
        setView(lng = 10.5, lat = 49.5, zoom = 6) %>% 
        addLayersControl(overlayGroups = "pts")
``
works for me.

**Comment by fpirotti** [comment]
You are right, everything works fine, popup not working was that I did not see the mouse pointer change upon hover, but clicking opens correctly the popup
Thanks a lot
