### ISSUE TITLE
How to use addLegend with leafgl

### ISSUE THREAD

**Issue by agila5** [r-spatial/leafgl#24]
Hi all. This is probably a stupid question, but do you have any example of how to use `leafgl` package with `addLegend` function of `leaflet` ? 

I need to create a map with a lot of LINESTRING objects colored according to a value and I have to add a legend at the bottom of the map explaining the meaning of the colors. I can easily create the map and color the lines but I don't know how to add a legend since the `addLegend` function requires  `pal` and `values` parameters while `addGlPolylines` requires just a rgb matrix.

**Comment by agila5** [comment]
It was really a stupid question since I already solved it. Sorry.

**Comment by maxlavoie** [comment]
For the risk for passing for a stupid ;-) can I ask you how you solved your problem?
thanks!
Martin

**Comment by maxlavoie** [comment]
Thank you for your example. It works well for a character or factor variables. But how would this work with a continuous variable? thank you.

**Comment by agila5** [comment]
I'm not sure. The easy way is to just `?cut` the continuous variables into several breaks (i.e. a factor).

**Comment by agila5** [comment]
> I'm not sure. The easy way is to just ?cut the continuous variables into several breaks (i.e. a factor).

Actually this was a stupid comment. You can easily apply `colour_values_rgb` to continuous variables, i.e.
``` r
library(colourvalues)
set.seed(1)
colour_values_rgb(rnorm(10), include_alpha = FALSE)
#>       [,1] [,2] [,3]
#>  [1,]   72   32  113
#>  [2,]   40  125  142
#>  [3,]   68    1   84
#>  [4,]  253  231   37
#>  [5,]   34  139  141
#>  [6,]   69    3   86
#>  [7,]   30  155  138
#>  [8,]   46  179  124
#>  [9,]   32  163  134
#> [10,]   63   73  137
```

<sup>Created on 2019-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This should solve also #30.
