### ISSUE TITLE
highlightOptions() not available with addGlPolygons?

### ISSUE THREAD

**Issue by pierredenelle** [r-spatial/leafgl#28]
In leaflet::addPolygons(), the argument highlightOptions() allows highlighting a part of the plot when the mouse is over it. This option does not seem implemented with addGlPolygons().

**Comment by tim-salabim** [comment]
No, and I wouldn't expect it to be anytime soon. If at all then it's likely going to be a minimum version of the leaflet functionality.

**Comment by pierredenelle** [comment]
Ok, thanks for your reply. I was not sure whether to open an issue or to mail you directly.

**Comment by tim-salabim** [comment]
Issue is always preferred as it's public and others can find it and participate of desired. 

Keeping this open as a reminder to investigate highlighting in webgl

**Comment by tim-salabim** [comment]
Closing this, as it's not on my priority list right now
