### ISSUE TITLE
how to make clusterOptions for addGlPoints

### ISSUE THREAD

**Issue by enricodata** [r-spatial/leafgl#29]
is it possible to add clusters to addGlPoints?

For example this is what can be done in leaflet:
 
leaflet(quakes) %>% addTiles() %>% **addMarkers**(
  clusterOptions = markerClusterOptions()
)

can we do something similar like the following?

leaflet(quakes) %>% addTiles() %>% **addGlPoints**(
  clusterOptions = markerClusterOptions()
)

**Comment by tim-salabim** [comment]
Nope, and I don't think we would need to, as the aim of **leafgl** is to provide a way to plot many points natively
