### ISSUE TITLE
How to use addLegend with leafgl (continuous variable)

### ISSUE THREAD

**Issue by maxlavoie** [r-spatial/leafgl#30]
It was first reported here (https://github.com/r-spatial/leafgl/issues/24). The author of the post did figure out by himself how to add a legend for a character or factor variable. But it does not work well with a continuous variable. I could use `cut()` to create a categorical value out of my continuous variable. But I was hoping there was a better (and nicer) way to do it.

Using this example, how would one add a legend?

> library(mapview)
> library(leaflet)
> library(leafgl)
> library(sf)
> library(colourvalues)
> 
> n = 1e6
> 
> df1 = data.frame(id = 1:n,
>                  x = rnorm(n, 10, 3),
>                  y = rnorm(n, 49, 1.8))
> 
> pts = st_as_sf(df1, coords = c("x", "y"), crs = 4326)
> 
> cols = colour_values_rgb(pts$id, include_alpha = FALSE) / 255
> 
> options(viewer = NULL)
> 
> system.time({
>   m = leaflet() %>%
>     addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
>     addGlPoints(data = pts, color = cols, group = "pts") %>%
>     addMouseCoordinates() %>%
>     setView(lng = 10.5, lat = 49.5, zoom = 6) %>% 
>     addLayersControl(overlayGroups = "pts")
> })
> 
> m

**Comment by tim-salabim** [comment]
Given that we are dealing with a leaflet map, you can add any legend in the same way you can to any other leaflet map. Please refer to the respective documentation of `leaflet::colorNumeric` and `leaflet::addLegend`
