### ISSUE TITLE
Pandoc does not recognize mime type of glsl files

### ISSUE THREAD

**Issue by jaredlander** [r-spatial/leafgl#31]
When using `{leafgl}` in a self-contained rmarkdown doc the following error occurs. This does not happen when the file is not self-contained.

```
Could not determine mime type for `~/R/R-3.6/x86_64-pc-linux-gnu/leafgl/htmlwidgets/Leaflet.glify/src/shader/fragment/dot.glsl'
Error: pandoc document conversion failed with error 63
```

This is an issue with Pandoc not being able to recognize the MIME type for `glsl`  files
https://github.com/jgm/pandoc/pull/6000

**Comment by tim-salabim** [comment]
@jaredlander thanks for the PR in the pandoc repo. Given that it is now merged, have you tried with the newest version?

**Comment by jaredlander** [comment]
Need to get the new build of Pandoc and have RStudio point to it, then will test this, hopefully tonight. Also made a request for RStudio to get the latest version of Pandoc (https://github.com/rstudio/rstudio/pull/5828).

Do you think with this fix you'll be uploading to CRAN soon?

**Comment by tim-salabim** [comment]
Re cran Update, @alandipert hast been doing a lot of stuff to get leaflgl properly integrated with leaflet. This has stalled a little recently, but my hope is to have a cran version before rstudio conf. Though this may be a little optimistic

**Comment by jaredlander** [comment]
That sounds like an excellent goal

**Comment by jaredlander** [comment]
Got the latest build of pandoc on my computer. Now I'm getting this error when building self-contained.

`pandoc: ~/R/R-3.6/x86_64-pc-linux-gnu/leafgl/htmlwidgets/Leaflet.glify/src/shader/fragment/aquare.glsl: openBinaryFile: does not exist (No such file or directory)`

The main takeaway is `aquare.glsl`. I'm guessing it really means `square.glsl`. Not sure where to go from here.

**Comment by tim-salabim** [comment]
Can you please try again after re-installing the package? Should be solved with https://github.com/r-spatial/leafgl/commit/1097220105874407bfe9bf760a2044bf712f60b9

**Comment by jaredlander** [comment]
Looks like it's working!

**Comment by jaredlander** [comment]
To speed performance I have been calling `leaflet()` with the argument `leafletOptions(preferCanvas=TRUE)`. Now that the points are using WebGL, is canvas no longer needed or perhaps even harming performance?

**Comment by tim-salabim** [comment]
Good question. I don't think it would affect things much, but I might be wrong (my JS is too limited). Let us know if you find any degragation.

**Comment by jaredlander** [comment]
Tried it both ways, didn't notice much. My generated html is pretty large already, so I doubt that's the bottleneck. But the good news is that the WebGL points are working faster than regular markers.

**Comment by tim-salabim** [comment]
Well, all that data needs to be stored somewhere... Closing this here. Feel free to re-open if necessary
