### ISSUE TITLE
setView is not automatic

### ISSUE THREAD

**Issue by jaredlander** [r-spatial/leafgl#32]
I don't have a good reprex right now, but I noticed that if I create a map with just elements from this package, the map doesn't zoom in properly, for instance.

```R
leaflet() %>%
    addTiles() %>%
    addGlPoints(data=point_data)
```

will be globally zoomed out. But

```R
leaflet() %>%
    addTiles() %>%
    addGlPoints(data=point_data) %>%
    addPolygons(data=poly_data)
```
will be zoomed in.

Guessing this has something to do with WebGL, but it's beyond me.

**Comment by tim-salabim** [comment]
Yes, I'll have a look what we need to do to autofocus. I still don't quite know how leaflet does it if we add multiple layers with different extents. WebGL is also beyond me :-)

**Comment by jaredlander** [comment]
I found a hacky way, by building a bounding box around my largest layer then manually calling `setView()` at the end of the map building code.

**Comment by tim-salabim** [comment]
I've just pushed a commit that should set the view automatically based on the provided data. Can you please re-test and see if it works for you?

**Comment by trafficonese** [comment]
works great!

**Comment by tim-salabim** [comment]
Closing here, as I think this is resolved. Feel free to re-open if not satidfied.

**Comment by jaredlander** [comment]
Glad this is working. I'm getting back into work on that project so will check it out.
