### ISSUE TITLE
renderLeafgl not working - object 'expr' not found

### ISSUE THREAD

**Issue by trafficonese** [r-spatial/leafgl#36]
When trying to use `renderLeafgl` in a shiny app, the following error message appears:

> Warning: Error in func: object 'expr' not found
> [No stack trace available]

Not exactly sure why `expr` gets lost. However, since the function is not really necessary as `renderLeaflet` works just fine and is also used everywhere in the examples / Readme, we could possibly omit the function at all and explain this in `leafglOutput`.

If we want to keep the function, we can either just reassign it (`renderLeafgl <- renderLeaflet`) or copy the code from `renderLeaflet`. In these 2 cases we would have to add `htmlwidgets` to the `Suggests`.

Or we set the default `quoted = TRUE`, which also fixes the problem and doesnt add any packages.

**Comment by tim-salabim** [comment]
I can't test this at the moment, because the new `glify.js` (v2.3.1) is giving me some grief. I'll test as soon as the issue is resolved.
