### ISSUE TITLE
Does Shiny input$map_shape_click work with glPolygons?

### ISSUE THREAD

**Issue by darwinsbeard** [r-spatial/leafgl#37]
Hello,
Firstly...awesome package, this has huge potential for me displaying my model mesh results, so keep up the excellent work!

However, I am having an issue inside of Shiny context, how do you capture the click event for individual polygons?

I have an observer that adds a polygon layer like this:
```
observe({
  req(grid_poly())  
leafletProxy('map') %>%
      clearShapes() %>%

 
  addGlPolygons(data = grid_poly(), 
              opacity = 1,
              color = cols,
              group = "Grid") 
})
```
Then I have another one that fires when a polygon is clicked and highlights it:

```
click_element <- eventReactive(input$map_shape_click, {

  input$map_shape_click$id
})

# highlight the clicked element
observe({

  req(click_element()) # do this if click_element() is not null

  # Add the clicked element to the map in aqua, and remove when a new one is clicked
  map <- leafletProxy('map') %>%
      removeShape('element') %>%
      addPolygons(data = grid_poly()[grid_poly()$id == click_element(), ],
                  fill = TRUE,
                  color = '#00ffff', opacity = 1, layerId = 'element')
})
```

But this doesn't seem to work.  But this did work using the generic AddPolygons() for leaflet.  Is this something inherently different about GLpoly's?

Thanks!

**Comment by trafficonese** [comment]
Yes, the addGl* functions currently don't emit the `map_shape_click` event (or any other event). I have some code to fix that. I'll try to open a PR with it in the coming days.

**Comment by darwinsbeard** [comment]
That would be fantastic, thank you!
