### ISSUE TITLE
Issue with color rendering addGLPolygons

### ISSUE THREAD

**Issue by ervanSTRI** [r-spatial/leafgl#42]
Hi Tim, 

I can't reproduce your example and change polygons color when usin addGlPolygons/points. I thought it might come from RStudio viewer, but the issue persists when displayed in a browser.
More importantly, I'd like to set my own color palette, but the colors aren't the right one when displayed (when they are). 
Thx for any hint.

```
library(mapview)
library(leaflet)
library(leafgl)
library(sf)
library(colourvalues)

n = 1e3

df1 = data.frame(id = 1:n,
                 x = rnorm(n, 10, 3),
                 y = rnorm(n, 49, 1.8),
                 col=rep(c(0,1),each=500))

pts = st_as_sf(df1, coords = c("x", "y"), crs = 4326)

cols = colour_values_rgb(pts$id, palette="plasma",include_alpha = FALSE) / 255
head(cols)
leaflet() %>%
    addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
    addGlPoints(data = pts, color = cols, group = "pts") %>%
    setView(lng = 10.5, lat = 49.5, zoom = 6) %>% 
    addLayersControl(overlayGroups = "pts")
```
![return this](https://i.imgur.com/DgpwzNg.png)

Then trying to set a user-definded color palette:
```
my_col <- cols
COL <- col2rgb(c("lightgrey","orange"))/255
my_col[which(df1$col==0),] <- rep(COL[,1],each=length(which(df1$col==0)))
my_col[which(df1$col!=0),] <- rep(COL[,2],each=length(which(df1$col==0)))

m <- leaflet() %>%
  addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
  addGlPoints(data = pts, color = my_col, group = "pts") %>%
  setView(lng = 10.5, lat = 49.5, zoom = 6) %>% 
  addLayersControl(overlayGroups = "pts")

mapshot(m,url="test_addGL_color.html")
```

**Comment by ervanSTRI** [comment]
To complement the second part of my question, regarding user-specific color code.
If I use the base function colourvalues::colour_values_rgb on a variable with only 2 levels (aka col in my example), I get a range of values (probably an interpolation, but based on what?) instead of getting 2 colors.
![](https://i.imgur.com/PWLlS3l.png)

I've tried to simply replace each color with the one I want, but then only a single color is shown on the maps
![](https://i.imgur.com/JA1vXVP.png)

**Comment by tim-salabim** [comment]
Yeah sorry that first issue is an oversight on my sight. I've changed the color parameter to fillColor to be more persistent with leaflet.

For the second issue I'd need to have a closer look, but will be away from my computer until next week

**Comment by ervanSTRI** [comment]
Thanks for your prompt reply. Let's catch up next week then. Cheers

**Comment by ervanSTRI** [comment]
Hi Tim,

I am really struggling with addGlPolygons. Unfortunately, it works randomly on my end while I am using the same piece of code. For instance, if you use this [data](https://www.dropbox.com/s/kngxnqfo3sx8lql/data_for_Tim.Rdata?dl=0), it doesn't display anything, whereas it works fine with mapview. Any idea on what I am doing wrong??
Thanks a lot.
E
```
load(~/data_for_Tim.Rdata)
leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron,group="Positron",layerId="Positron") %>%
  addGlPolygons(data = A, group = "IST",popup="idx",fillColor=col1,opacity=1) %>%
  addLegend(pal =  col2, values=A$idx,group = "IST", position = "topright",opacity=1,title="IST") %>% addLayersControl(baseGroups= c("Positron","Esri","OpenStreet"),overlayGroups = c("grid.id","ha to add","IST","Quality"),position="topleft")

```
vs.
`mapview::mapview(A,viewer.suppress=F)`

**Comment by tim-salabim** [comment]
A little digging reveals that you have one empty polygon in your data:

``` r
library(leaflet)
library(leafgl)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.1.0, PROJ 7.0.0

load("~/software/testing/leafgl/data_for_Tim.Rdata")  # data set is called A 
col1 = colourvalues::colour_values_rgb(A$idx, palette = "viridis",include_alpha = FALSE)/255
col2 <- colorNumeric(palette = "viridis",A$idx)

table(st_is_empty(A))
#> 
#> FALSE  TRUE 
#>  9999     1

leaflet() %>% 
    addProviderTiles(provider = providers$CartoDB.Positron,group="Positron",layerId="Positron") %>%
    addGlPolygons(data = A[!(st_is_empty(A)), ], group = "IST",popup="idx",fillColor=col1,opacity=1) %>%
    addLegend(pal =  col2, values=A$idx,group = "IST", position = "topright",opacity=1,title="IST") %>% addLayersControl(baseGroups= c("Positron","Esri","OpenStreet"),overlayGroups = c("grid.id","ha to add","IST","Quality"),position="topleft")
#> Warning in checkDim(x, data): Number of rows of color matrix does not match number of data rows.
#>   Just the first row is taken.
#> Registered S3 method overwritten by 'jsonlite':
#>   method     from   
#>   print.json jsonify
```

![](https://i.imgur.com/5jqZMPd.png)

<sup>Created on 2020-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tim-salabim** [comment]
Not sure why the reprex above doesn't render the map correctly, but on my machine the data is plotted just nicely

**Comment by tim-salabim** [comment]
As for your first question, it works if you use `fillColor` instead of `color`. 

As for your second question about color interpolation, I'd need a reproducible example.

Please also do not mix issues (as you do here) in the future. This is not a help site like SO, this is a software repo where bugs and feature requests should be posted. And to keep things concise and organised, we need to devote one issue to one bug. Otherwise it will be much harder for others to find solutions if they encounter something similar.

**Comment by ervanSTRI** [comment]
Thanks. Sorry for mixing issues here. Will move on SO for further questions. BR
