### ISSUE TITLE
leafglOutput not rendering points

### ISSUE THREAD

**Issue by zackarno** [r-spatial/leafgl#44]
I can make a leaflet object with addGlPoints that will work and open in a browser perfectly. But When I use the leafglOutput in a shiny app it doesn't render the points, but rather just the leaflet map with tiles. This issue occurs even when I copy and paste the leafglOutput example from your github into shiny app on my computer :

    library(mapview)
    library(leaflet)
    library(leafgl)
    library(sf)

    n = 1e4
    df1 = data.frame(id = 1:n,
                     x = rnorm(n, 10, 3),
                     y = rnorm(n, 49, 1.8))
    pts = st_as_sf(df1, coords = c("x", "y"), crs = 4326)

    m = leaflet() %>%
        addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
        addGlPoints(data = pts, group = "pts") %>%
        addMouseCoordinates() %>%
        setView(lng = 10.5, lat = 49.5, zoom = 6) %>%
        addLayersControl(overlayGroups = "pts")

    ui <- fluidPage(
        leafglOutput("mymap")
    )

    server <- function(input, output, session) {
        output$mymap <- renderLeaflet(m)
    }

    shinyApp(ui, server)

**Comment by tim-salabim** [comment]
What's your `devtools::session_info()`?

**Comment by zackarno** [comment]
Thanks for the reply, here it is the session info

- Session info --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       Pacific/Auckland            
 date     2020-06-18                  

- Packages ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package           * version date       lib source                           
 assertthat          0.2.1   2019-03-21 [1] CRAN (R 3.6.0)                   
 backports           1.1.8   2020-06-17 [1] CRAN (R 3.6.0)                   
 base64enc           0.1-3   2015-07-28 [1] CRAN (R 3.6.0)                   
 brew                1.0-6   2011-04-13 [1] CRAN (R 3.6.0)                   
 broom               0.5.6   2020-04-20 [1] CRAN (R 3.6.3)                   
 butteR              0.1.0   2020-06-16 [1] local                            
 callr               3.4.3   2020-03-28 [1] CRAN (R 3.6.3)                   
 cellranger          1.1.0   2016-07-27 [1] CRAN (R 3.6.0)                   
 class               7.3-17  2020-04-26 [1] CRAN (R 3.6.3)                   
 classInt            0.4-3   2020-04-07 [1] CRAN (R 3.6.3)                   
 cli                 2.0.2   2020-02-28 [1] CRAN (R 3.6.3)                   
 codetools           0.2-16  2018-12-24 [2] CRAN (R 3.6.0)                   
 colorspace          1.4-1   2019-03-18 [1] CRAN (R 3.6.0)                   
 crayon              1.3.4   2017-09-16 [1] CRAN (R 3.6.0)                   
 crosstalk           1.1.0.1 2020-03-13 [1] CRAN (R 3.6.3)                   
 data.table          1.12.8  2019-12-09 [1] CRAN (R 3.6.3)                   
 DBI                 1.1.0   2019-12-15 [1] CRAN (R 3.6.3)                   
 dbplyr              1.4.3   2020-04-19 [1] CRAN (R 3.6.3)                   
 desc                1.2.0   2018-05-01 [1] CRAN (R 3.6.0)                   
 devtools            2.3.0   2020-04-10 [1] CRAN (R 3.6.3)                   
 digest              0.6.25  2020-02-23 [1] CRAN (R 3.6.3)                   
 dplyr             * 1.0.0   2020-05-29 [1] CRAN (R 3.6.3)                   
 e1071               1.7-3   2019-11-26 [1] CRAN (R 3.6.3)                   
 ellipsis            0.3.1   2020-05-15 [1] CRAN (R 3.6.3)                   
 evaluate            0.14    2019-05-28 [1] CRAN (R 3.6.0)                   
 extrafont           0.17    2014-12-08 [1] CRAN (R 3.6.0)                   
 extrafontdb         1.0     2012-06-11 [1] CRAN (R 3.6.0)                   
 fansi               0.4.1   2020-01-08 [1] CRAN (R 3.6.3)                   
 fastmap             1.0.1   2019-10-08 [1] CRAN (R 3.6.2)                   
 forcats           * 0.5.0   2020-03-01 [1] CRAN (R 3.6.3)                   
 fs                  1.4.1   2020-04-04 [1] CRAN (R 3.6.3)                   
 gdtools             0.2.2   2020-04-03 [1] CRAN (R 3.6.3)                   
 generics            0.0.2   2018-11-29 [1] CRAN (R 3.6.0)                   
 ggplot2           * 3.3.1   2020-05-28 [1] CRAN (R 3.6.3)                   
 glue                1.4.1   2020-05-13 [1] CRAN (R 3.6.3)                   
 gtable              0.3.0   2019-03-25 [1] CRAN (R 3.6.0)                   
 haven               2.2.0   2019-11-08 [1] CRAN (R 3.6.3)                   
 hms                 0.5.3   2020-01-08 [1] CRAN (R 3.6.3)                   
 hrbrthemes        * 0.8.0   2020-03-06 [1] CRAN (R 3.6.3)                   
 htmltools           0.5.0   2020-06-16 [1] CRAN (R 3.6.0)                   
 htmlwidgets         1.5.1   2019-10-08 [1] CRAN (R 3.6.3)                   
 httpuv              1.5.2   2019-09-11 [1] CRAN (R 3.6.3)                   
 httr                1.4.1   2019-08-05 [1] CRAN (R 3.6.3)                   
 jsonify             1.2.1   2020-06-02 [1] CRAN (R 3.6.3)                   
 jsonlite            1.6.1   2020-02-02 [1] CRAN (R 3.6.3)                   
 KernSmooth          2.23-17 2020-04-26 [1] CRAN (R 3.6.3)                   
 knitr               1.28    2020-02-06 [1] CRAN (R 3.6.3)                   
 later               1.0.0   2019-10-04 [1] CRAN (R 3.6.3)                   
 lattice             0.20-41 2020-04-02 [1] CRAN (R 3.6.3)                   
 lazyeval            0.2.2   2019-03-15 [1] CRAN (R 3.6.0)                   
 leafem              0.1.1   2020-04-05 [1] CRAN (R 3.6.3)                   
 leafgl            * 0.1.1   2020-06-17 [1] Github (r-spatial/leafgl@97f95ef)
 leaflet           * 2.0.3   2019-11-16 [1] CRAN (R 3.6.3)                   
 leaflet.extras    * 1.0.0   2018-04-21 [1] CRAN (R 3.6.0)                   
 leaflet.providers   1.9.0   2019-11-09 [1] CRAN (R 3.6.3)                   
 leafpop           * 0.0.5   2019-12-09 [1] CRAN (R 3.6.3)                   
 lifecycle           0.2.0   2020-03-06 [1] CRAN (R 3.6.3)                   
 lubridate           1.7.8   2020-04-06 [1] CRAN (R 3.6.3)                   
 magrittr            1.5     2014-11-22 [1] CRAN (R 3.6.0)                   
 mapview           * 2.7.8   2020-04-07 [1] CRAN (R 3.6.3)                   
 memoise             1.1.0   2017-04-21 [1] CRAN (R 3.6.0)                   
 mime                0.9     2020-02-04 [1] CRAN (R 3.6.2)                   
 modelr              0.1.7   2020-04-30 [1] CRAN (R 3.6.0)                   
 munsell             0.5.0   2018-06-12 [1] CRAN (R 3.6.0)                   
 nlme                3.1-147 2020-04-13 [1] CRAN (R 3.6.3)                   
 packrat             0.5.0   2018-11-14 [1] CRAN (R 3.6.0)                   
 pillar              1.4.4   2020-05-05 [1] CRAN (R 3.6.3)                   
 pkgbuild            1.0.8   2020-05-07 [1] CRAN (R 3.6.3)                   
 pkgconfig           2.0.3   2019-09-22 [1] CRAN (R 3.6.0)                   
 pkgload             1.1.0   2020-05-29 [1] CRAN (R 3.6.3)                   
 plotly            * 4.9.2.1 2020-04-04 [1] CRAN (R 3.6.3)                   
 png                 0.1-7   2013-12-03 [1] CRAN (R 3.6.0)                   
 prettyunits         1.1.1   2020-01-24 [1] CRAN (R 3.6.3)                   
 processx            3.4.2   2020-02-09 [1] CRAN (R 3.6.3)                   
 promises            1.1.0   2019-10-04 [1] CRAN (R 3.6.3)                   
 ps                  1.3.3   2020-05-08 [1] CRAN (R 3.6.3)                   
 purrr             * 0.3.4   2020-04-17 [1] CRAN (R 3.6.3)                   
 R6                  2.4.1   2019-11-12 [1] CRAN (R 3.6.3)                   
 raster              3.1-5   2020-04-19 [1] CRAN (R 3.6.3)                   
 Rcpp                1.0.4.6 2020-04-09 [1] CRAN (R 3.6.3)                   
 readr             * 1.3.1   2018-12-21 [1] CRAN (R 3.6.0)                   
 readxl              1.3.1   2019-03-13 [1] CRAN (R 3.6.2)                   
 remotes             2.1.1   2020-02-15 [1] CRAN (R 3.6.2)                   
 reprex              0.3.0   2019-05-16 [1] CRAN (R 3.6.1)                   
 rlang               0.4.6   2020-05-02 [1] CRAN (R 3.6.3)                   
 rmarkdown           2.1     2020-01-20 [1] CRAN (R 3.6.3)                   
 rprojroot           1.3-2   2018-01-03 [1] CRAN (R 3.6.0)                   
 rsconnect           0.8.16  2019-12-13 [1] CRAN (R 3.6.3)                   
 rstudioapi          0.11    2020-02-07 [1] CRAN (R 3.6.3)                   
 Rttf2pt1            1.3.8   2020-01-10 [1] CRAN (R 3.6.2)                   
 rvest               0.3.5   2019-11-08 [1] CRAN (R 3.6.3)                   
 satellite           1.0.2   2019-12-09 [1] CRAN (R 3.6.3)                   
 scales              1.1.1   2020-05-11 [1] CRAN (R 3.6.3)                   
 sessioninfo         1.1.1   2018-11-05 [1] CRAN (R 3.6.0)                   
 sf                * 0.9-4   2020-06-13 [1] CRAN (R 3.6.3)                   
 shiny             * 1.4.0.2 2020-03-13 [1] CRAN (R 3.6.3)                   
 shinydashboard    * 0.7.1   2018-10-17 [1] CRAN (R 3.6.3)                   
 sourcetools         0.1.7   2018-04-25 [1] CRAN (R 3.6.0)                   
 sp                  1.4-2   2020-05-20 [1] CRAN (R 3.6.3)                   
 stringi             1.4.6   2020-02-17 [1] CRAN (R 3.6.2)                   
 stringr           * 1.4.0   2019-02-10 [1] CRAN (R 3.6.0)                   
 svglite             1.2.3   2020-02-07 [1] CRAN (R 3.6.3)                   
 systemfonts         0.2.0   2020-04-16 [1] CRAN (R 3.6.3)                   
 testthat            2.3.2   2020-03-02 [1] CRAN (R 3.6.3)                   
 tibble            * 3.0.1   2020-04-20 [1] CRAN (R 3.6.3)                   
 tidyr             * 1.0.2   2020-01-24 [1] CRAN (R 3.6.3)                   
 tidyselect          1.1.0   2020-05-11 [1] CRAN (R 3.6.3)                   
 tidyverse         * 1.3.0   2019-11-21 [1] CRAN (R 3.6.3)                   
 units               0.6-7   2020-06-13 [1] CRAN (R 3.6.3)                   
 usethis             1.6.1   2020-04-29 [1] CRAN (R 3.6.3)                   
 uuid                0.1-4   2020-02-26 [1] CRAN (R 3.6.3)                   
 vctrs               0.3.1   2020-06-05 [1] CRAN (R 3.6.3)                   
 viridisLite         0.3.0   2018-02-01 [1] CRAN (R 3.6.0)                   
 webshot             0.5.2   2019-11-22 [1] CRAN (R 3.6.3)                   
 withr               2.2.0   2020-04-20 [1] CRAN (R 3.6.3)                   
 xfun                0.14    2020-05-20 [1] CRAN (R 3.6.3)                   
 xml2                1.3.2   2020-04-23 [1] CRAN (R 3.6.3)                   
 xtable              1.8-4   2019-04-21 [1] CRAN (R 3.6.0)                   
 yaml                2.2.1   2020-02-01 [1] CRAN (R 3.6.3)                   

[1] C:/Users/Felipe Ponce/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.0/library

**Comment by tim-salabim** [comment]
Can you post a screenshot of the browser console? In most browsers you can open it by pressing either `ctrl + shift + i` or `F12`

**Comment by tim-salabim** [comment]
So, I just tested in:

* firefox (works)
* opera (works)
* chrome (works)
* chromium (works)
* brave (doesn't work)

If I disable the native ad-blocking in brave browser (called shields) it works too.

So I am assuming that you don't see the points because you have some sort of ad blocking enabled. 

Can you please try to disable and see if it solves your issue?

**Comment by zackarno** [comment]
Hey thanks for looking into this. I just realized that it actually does work when I open it in the browser, just not in the r studio viewer. I also now see that you do document this issue your githubs readme. Opening the app in a browser rather than rstudio viewer is fine solution for me. Thanks again!
