### ISSUE TITLE
Support simpleCircle rendering

### ISSUE THREAD

**Issue by AB-Kent** [r-spatial/leafgl#53]
I would like to use `leafgl` to render points without borders. The `simpleCircle` fragment shader in `leaflet.glify` does this. Can this be exposed as a user option?

Using the `simpleCircle` shader requires adding 
```
    fragmentShaderSource: () => {
        return L.glify.shader.fragment.simpleCircle;
      }
```
to the call to `L.glify.points` in `addGlifyPoints.js`. What is the best way to do that optionally, so the existing functionality is preserved?

Thanks!

**Comment by AB-Kent** [comment]
Hi, would you consider a pull request along the lines of the above changeset? It supports any fragment shader defined in Leaflet.gliphy while preserving the existing functionality. If you approve I'll make corresponding changes to `addGlPointsSrc`.

**Comment by tim-salabim** [comment]
@AB-Kent yes, a PR would be great.
