### ISSUE TITLE
test-leafgl-colors.R fails if {colourvalues} not installed

### ISSUE THREAD

**Issue by AB-Kent** [r-spatial/leafgl#55]
Running `test-leafgl-colors.R` without the `colourvalues` package installed gives this error:
```
-- Error (test-leafgl-colors.R:153:3): Formula as color ------------------------
Error: invalid color name 'rainbow'
Backtrace:
 1. `%>%`(...) test-leafgl-colors.R:153:2
 2. leafgl::addGlPoints(...)
 4. leafgl::makeColorMatrix.formula(fillColor, data, palette = palette) C:/Research/leafgl/R/utils-color.R:52:2
 6. leafgl::makeColorMatrix.integer(x, data, palette, ...) C:/Research/leafgl/R/utils-color.R:52:2
 8. grDevices::col2rgb(pal(x), alpha = FALSE)
```

The problem seems to be that `leaflet::colorNumeric` doesn't recognize `"rainbow"` as a valid palette here:
https://github.com/r-spatial/leafgl/blob/51e31b18b5a0cbb06882a019a219caf0d064d1da/R/utils-color.R#L68)

Changing the call to `palette="viridis"` makes the test pass.

**Comment by trafficonese** [comment]
Indeed, `rainbow` is not a valid palette name. Thank you!
