### ISSUE TITLE
Warnings in test-leafgl-colors.R

### ISSUE THREAD

**Issue by AB-Kent** [r-spatial/leafgl#56]
Running under R 4.0.3, `test-leafgl-colors.R` gives several warnings such as this:
```
-- Warning (test-leafgl-colors.R:456:3): List as color -------------------------
Length of color vector does not match number of data rows.
  The vector is repeated to match the number of rows.
Backtrace:
 1. `%>%`(...) test-leafgl-colors.R:456:2
 2. leafgl::addGlPoints(...)
 4. leafgl::makeColorMatrix.list(fillColor, data, palette = palette) C:/Research/leafgl/R/utils-color.R:52:2
 6. leafgl::makeColorMatrix.numeric(x, data, palette, ...) C:/Research/leafgl/R/utils-color.R:52:2
 7. leafgl::checkDim(x, data) C:/Research/leafgl/R/utils-color.R:67:6
```

Although this is reported as a warning, it seems to be a bug as it results in the wrong colors being used.

The problem is in `makeColorMatrix.list`:
https://github.com/r-spatial/leafgl/blob/51e31b18b5a0cbb06882a019a219caf0d064d1da/R/utils-color.R#L131

In R 4.0 the class of a matrix is `c("matrix" "array")` so the above test fails.

**Comment by tim-salabim** [comment]
@trafficonese I believe this is code you introduced?

**Comment by trafficonese** [comment]
@AB-Kent Thanks for the catch.
Could you retry the dev version and confirm that this is fixed?

**Comment by AB-Kent** [comment]
@trafficonese Yes, looks good to me.
