### ISSUE TITLE
Use leagfl to render Mapbox/Maptiler vector tiles?

### ISSUE THREAD

**Issue by mbacou** [r-spatial/leafgl#63]
Hi @tim-salabim, I've been looking for a solution to render vector tile basemaps in R leaflet (e.g. https://www.maptiler.com/maps/#topo//vector/1/0/0) which requires the [leafetGL plugin](https://github.com/mapbox/mapbox-gl-leaflet). Is it maybe possible using this package (or another)?
Thx!

**Comment by tim-salabim** [comment]
As far as I know, the lefletGL plugin you me too is the only way to use those background maps with leaflet and I am not aware of any r package that wraps it. This package (leafgl) is exclusively for overlays (polygons etc.). As far as I know, package mapdeck provides functionality to render vector tile basemaps. Is there a specific reason that you want this for the leaflet framework? If not, mapdeck is well worth checking out.

**Comment by mbacou** [comment]
Hi Tim, thanks for the clarification.
Yes indeed I can render these vector tiles with mapdeck and [deckgl](https://github.com/crazycapivara/deckgl), but I have a specific use case for overlaying WMS raster tiles as well for a Shiny app, and while easy with R leaflet, it's not obvious how to do that with these 2 packages. 
Guess I might have to resort to a hybrid JavaScript + R approach.

**Comment by tim-salabim** [comment]
Well, if you're already considering JS + R, you might want to think about wrapping leafletGL in a package (or make a PR here) so that other people can also use it?

**Comment by mbacou** [comment]
Slightly ambitious (-: but if you think this added functionality would fit well here and is generally useful, can give it shot. 

I've also considered extending the [Cesium](https://github.com/r-spatial/cesium) wrapper for R that you have also written, which I believe has good support for displaying vector tiles and WMS/WMTS sources (in addition to 3D terrain). Any opinion as to which JS library might is a better candidate?

Thx!

**Comment by tim-salabim** [comment]
Oh, that's a nice thought. If cesium plays well with vector tiles, then it might be a good idea to update and expand it. It should get more love.

**Comment by trafficonese** [comment]
@mbacou This might be of interest: https://github.com/rstudio/leaflet.mapboxgl

It's an R-wrapper for the `mapbox-gl-leaflet` JS library.

**Comment by tim-salabim** [comment]
Good call @trafficonese. There's also https://github.com/walkerke/mapboxapi by @walkerke

**Comment by mbacou** [comment]
Thanks to you both, had missed these! Joe Cheng's extension looks like just what I need.
