### ISSUE TITLE
Support for layer ordering

### ISSUE THREAD

**Issue by DanWismer** [r-spatial/leafgl#64]
Hi,

Wondering if this package can support AddMapPane and options = pathOptions(pane = "somename")) for layering lines on top of polygons?

Thanks!

**Comment by trafficonese** [comment]
The latest version of `Leaflet.glify` accepts a `pane` argument but it is currently not possible via leafgl. 
If you feel comfortable with JS and R you can try to come up with a PR which accepts that argument, otherwise I can try to work something out..
