### ISSUE TITLE
Case study with very large line geometry layer

### ISSUE THREAD

**Issue by h-a-graham** [r-spatial/leafgl#70]
Hey @tim-salabim , 
Further to the [tweet](https://twitter.com/hughagraham/status/1502014688376336394) I posted about deck.gl and leafgl performace, here is some testing across {leafgl}, [{mapdeck}](https://github.com/SymbolixAU/mapdeck) and [{rdeck}](https://github.com/anthonynorth/rdeck). 

I've hosted an example dataset on s3 which I'll leave up for a while for working on incase it is a useful test case. It is the [Ordnance Survey Open Rivers Network](https://www.ordnancesurvey.co.uk/business-government/products/open-map-rivers), split into smaller sections and subsequently simplified a bit wth `rmapshaper::ms_simplify` with some additional Hyrological attributes that I've derived. Theoretically, I could aggregate the data more to reduce the number of features but ideally I'd like to retain this level of detail.

In the following example, I'll take a filtered set of the data and test both this and the full dataset.

``` r
library(sf)
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
library(sfarrow)
library(viridisLite)
library(leaflet)
library(leafgl)
```

``` r
if (!file.exists('rivers_gb.paraquet')) {
  download.file('https://beaver-net-app.s3.eu-west-2.amazonaws.com/gb_rivers/rivers_gb.paraquet',
                'rivers_gb.paraquet')
}

gb_rivers <-sfarrow::st_read_parquet('rivers_gb.paraquet')

## If the paraquet file isn't working then try this instead:
# if (!file.exists('rivers_gb.rds')) {
#   download.file('https://beaver-net-app.s3.eu-west-2.amazonaws.com/gb_rivers/rivers_gb.rds',
#                 'rivers_gb.rds')
# }
# gb_rivers <- readRDS('rivers_gb.rds')

sw_region <- st_bbox(c(xmin = -6.014, ymin = 49.821,
                       xmax =  -3.038 , ymax = 51.343),
                     crs = st_crs(4326)) |>
  st_as_sfc()

rivers_sw <- gb_rivers |>
  st_filter(sw_region)
```

``` r
rivers_leaflet <- function(riv_lines){
  pal <- colorQuantile(
    palette = magma(256),
    domain = riv_lines$Drain_Area,
    n=8)

  # Make colours and labels for legend
  pal_colors <- unique(pal(sort(riv_lines$Drain_Area))) # hex codes
  pal_labs <- round(quantile(riv_lines$Drain_Area, seq(0, 1, 1/8))) # depends on n from pal
  pal_labs_chr <- paste(lag(pal_labs), pal_labs, sep = " - ")[-1] # first lag is NA

  # make leaflet map
  leaflet() |>
    addProviderTiles(provider = providers$CartoDB.DarkMatter) |>
    addGlPolylines(riv_lines,
                   color= ~pal(Drain_Area),
                   weight=0.5,
                   group="DrainArea",
                   layerId='lines1') |>
    addLegend(colors = pal_colors,
              labels = pal_labs_chr,
              opacity = 7,
              title = "Upstream Catchment Area",
              group="DrainArea")
}

rivers_leaflet(rivers_sw) # works perfectly...
#> Registered S3 method overwritten by 'jsonify':
#>   method     from    
#>   print.json jsonlite
```

![leafgl_sw](https://user-images.githubusercontent.com/43027949/157880999-b8219975-1a0f-42f2-a75a-621392abeae9.png)

``` r
# rivers_leaflet(gb_rivers) # For me, this doesn't render any lines (only the base map)...
```

``` r
library(mapdeck) # from CRAN
# set_token()

# rivers_sw_copy <- rivers_sw # make a copy as was being mangled by mapdeck
rivers_mapdeck <- function(riv_lines){
  mapdeck(style = mapdeck_style('dark'), pitch = 0 ) |>
    add_path(data=riv_lines,
             polyline='geom',
             stroke_colour='Drain_Area',
             stroke_width=2,
             palette = 'magma',
             legend=TRUE,
             legend_options = list(title="Upstream Catchment Area"),
             width_min_pixels=2,
             tooltip = 'Drain_Area')

}


rivers_mapdeck(rivers_sw) # works 
```

![mapdeck_sw](https://user-images.githubusercontent.com/43027949/157884704-f8f6ab82-2b5e-453f-851f-f02cbecdaa2e.png)

``` r
rivers_mapdeck(gb_rivers) # throws error
#> Error in rcpp_path_interleaved(data, l, list_cols, digits, "path"): upper value must be greater than lower value
```

``` r
library(rdeck)
#?mapbox_access_token()

rivers_rdeck <- function(riv_lines){
  rdeck( map_style = mapbox_dark(), initial_bounds = st_bbox(riv_lines),
         picking_radius = 2) |>
    add_path_layer(
      name = "Upstream Catchment Area",
      group_name= "Upstream Catchment Area",
      data = riv_lines,
      get_path = geom,
      get_color = scale_color_quantile(
        col = Drain_Area,
        palette = magma(8)),
      pickable = TRUE,
      auto_highlight = TRUE,
      width_scale = 15,
      width_min_pixels = 2,
      blending_mode = "normal",
      visibility_toggle = TRUE,
      tooltip = c(Drain_Area, Str_order,Width_m, Slope_perc),
    )

}

# Here both work...
rivers_rdeck(rivers_sw)
```

![rdeck_sw](https://user-images.githubusercontent.com/43027949/157884932-b6a50d92-4351-45d4-8e53-850914fbcfc3.png)

``` r
rivers_rdeck(gb_rivers)
```

![rdeck_gb](https://user-images.githubusercontent.com/43027949/157884885-0f0702fc-a0d2-44be-bb17-b9a1940b5ad4.png)

<sup>Created on 2022-03-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

So, as it stands, I have only successfully rendered the full dataset with {rdeck}. If possible I'd love to stick with leafgl for this so really appreciate any insight you can share here. Thanks again for this great package and offering to take a look at this.

Cheers,
Hugh

**Comment by h-a-graham** [comment]
Tiny bit of extra context. I increased the subset size for the {leafgl} test and It can render much more than the subset given in the example above but once, this stage is reached (pictured below n = 792884 features) the interaction becomes laggy.
![image](https://user-images.githubusercontent.com/43027949/157899463-5032f2bf-7e5d-49d4-ad0e-a5542a3cd65c.png)

**Comment by tim-salabim** [comment]
Hm, I think this is beyond my coding capabilities and seems to stem from the upstream lib.
The error (actually a warning that leads to an error down the road) I'm seeing in the browser console states:

`GL_INVALID_VALUE: Index must be less than MAX_VERTEX_ATTRIBS.` - see also screenshot below.

@h-a-graham are you seeing a similar warning/error in the browser when lines are not rendering?

@robertleeplummerjr any ideas?

![image](https://user-images.githubusercontent.com/2826432/157909967-8e86c004-51d5-46f7-b37f-d202fd41ae8e.png)

**Comment by h-a-graham** [comment]
Thanks Tim,

Yes, same error for me too: 
![image](https://user-images.githubusercontent.com/43027949/157911081-c662b854-b831-483e-a0ee-744d999d161f.png)

Cheers!

**Comment by tim-salabim** [comment]
@robertleeplummerjr never mind. This is a problem of the data...

@h-a-graham I figured out why things are misbehaving. There are some "bad" geometries in the data:

```r
na_idx = which(is.na(st_dimension(gb_rivers)))
na_idx
# [1]   11729  110519  151966  169020  504767  518221  554334  578253  578304  712961  750363  821643  821645
# [14]  826205  836068  895926 1053581
gb_rivers = gb_rivers[-na_idx, ]
```
Removing those will render the map just fine. As you state above, though, it does not response nicely anymore. This is due to the fact that all data is being written to the .html file as geojson which just makes the file too big. For this, we have an argument `src`. If set to `TRUE` this will attach the data (and possibly color, popup, label) parts to the page rather than include it. This makes the map much more responsive.

```
rivers_leaflet <- function(riv_lines){
  pal <- colorQuantile(
    palette = magma(256),
    domain = riv_lines$Drain_Area,
    n=8)

  # Make colours and labels for legend
  pal_colors <- unique(pal(sort(riv_lines$Drain_Area))) # hex codes
  pal_labs <- round(quantile(riv_lines$Drain_Area, seq(0, 1, 1/8))) # depends on n from pal
  pal_labs_chr <- paste(lag(pal_labs), pal_labs, sep = " - ")[-1] # first lag is NA
  
  # make leaflet map
  leaflet() |>
    addProviderTiles(provider = providers$CartoDB.DarkMatter) |>
    addGlPolylines(riv_lines,
                   src = TRUE,
                   color= ~pal(Drain_Area),
                   weight=0.5,
                   group="DrainArea",
                   layerId='lines1') |>
    addLegend(colors = pal_colors,
              labels = pal_labs_chr,
              opacity = 7,
              title = "Upstream Catchment Area",
              group="DrainArea")
}
```
![image](https://user-images.githubusercontent.com/2826432/157923776-22d88dbb-3aa7-466f-a1c9-88e2f70cc79a.png)

**Comment by tim-salabim** [comment]
Note also, that this amount of data frequently crashes my RStudio. So setting `options(viewer = NULL)` is advised

**Comment by robertleeplummerjr** [comment]
This is beautiful!

**Comment by robertleeplummerjr** [comment]
Does it crash the browser?

**Comment by tim-salabim** [comment]
No browser is fine. It's more than a million Linestrings 😀 so very impressive! Thanks for all the Leaflet.glify work!!

**Comment by h-a-graham** [comment]
YES! that works perfectly now - I'm actually blown away by how well this works! Thanks so much for taking the time to look into this, you're a life saver!

**Comment by tim-salabim** [comment]
You're more than welcome. I'm always interested in taking these things further. One more thing to note also is that you can also pass a `digits` argument via `...` so that coordinates are rounded to that number of digits. In your case that may help further as the coordinates of the original data have 10+ digits which seems like overkill.

**Comment by h-a-graham** [comment]
Thanks for checking this, I thought it might as the error in the console matched the browser error when using leafgl. So many great options to choose from now! Cheers!

**Comment by anthonynorth** [comment]
HI @h-a-graham, 

Try using vector tiles when visualising larger datasets. There's more tooling involved and it takes effort, but the result is well worth it. In rdeck, you can use vector tiles pretty much the same way as local data, only limitation (currently) is you need to specify your scale limits (or category levels) explicitly. Quantile scale of course isn't possible without a copy of the data, but you can fake one using a threshold scale, which I have done below.

Note: I had remove other attributes and reduce the precision of the `drain_area` (nearest 0.5) to fit the data under the 500k tile limit.

```r
library(rdeck)

rdeck(
  map_style = mapbox_dark(),
  # pre-computed bounds
  initial_bounds = sf::st_bbox(
    c(xmin = -6.975690, ymin = 49.975074, xmax = 1.739668, ymax = 58.686302),
    crs = 4326
  ),
  picking_radius = 2,
  layer_selector = TRUE
) |>
  add_mvt_layer(
    name = "Upstream Catchment Area (compact)",
    # source data from https://beaver-net-app.s3.eu-west-2.amazonaws.com/gb_rivers/rivers_gb.rds
    data = tile_json("anthony-north.2izrjjdl"),
    get_line_color = scale_color_threshold(
      col = drain_area,
      palette = viridis::magma,
      # pre-computed quantile breaks & limits
      breaks = c(0, 1.11, 3.1, 7.98, 31.79, 10378.65),
      limits = c(0, 10378.65)
    ),
    get_line_width = 15,
    line_width_min_pixels = 0.75,
    pickable = TRUE,
    auto_highlight = TRUE,
    tooltip = drain_area,
  )
```

Data-processing "pipeline" (and my first attempt with more data and keeping precision) can be found in this gist: https://gist.github.com/anthonynorth/bb018981775758c44aa2101166b26646
