### ISSUE TITLE
src=TRUE issue with addGL... when using Shiny

### ISSUE THREAD

**Issue by h-a-graham** [r-spatial/leafgl#71]
Hi @tim-salabim, 

Further to the previous issue (https://github.com/r-spatial/leafgl/issues/70), where you suggested using the `src=TRUE` with 
`addGlPolylines`, `addGlPoints`, etc. in order to improve the performance. This works great for me apart from when in a shiny app. 

The following works when `src=FALSE` but when TRUE no features are rendered and the error message: `Unknown method addGlifyPointsSrc` is given. Here is the message from Chrome:
![image](https://user-images.githubusercontent.com/43027949/159002633-eb815df9-35fa-478e-99d7-1d646bd96bfb.png)

``` r
library(leaflet)
library(leafgl)
library(sf)
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
library(shiny)

n = 1e6

df1 = data.frame(id = 1:n,
                 x = rnorm(n, 10, 3),
                 y = rnorm(n, 49, 1.8))

pts = st_as_sf(df1, coords = c("x", "y"), crs = 4326)

options(viewer = NULL) # view in browser

m = leaflet() %>%
  addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
  addGlPoints(data = pts, group = "pts", src=TRUE) %>% # src set to TRUE
  setView(lng = 10.5, lat = 49.5, zoom = 4) %>%
  addLayersControl(overlayGroups = "pts")

ui <- fluidPage(
  leafglOutput("mymap")
)
#> Registered S3 method overwritten by 'jsonlite':
#>   method     from   
#>   print.json jsonify

server <- function(input, output, session) {
  output$mymap <- renderLeaflet(m)
}

shinyApp(ui, server)
#> 
#> Listening on http://127.0.0.1:8785
```
<sup>Created on 2022-03-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Do you know of any workarounds for this?

Many thanks!
Hugh

**Comment by tim-salabim** [comment]
I'll look into it over the weekend.

**Comment by h-a-graham** [comment]
Thankyou Tim!

**Comment by tim-salabim** [comment]
Should work now. Was a naming clash between the standard `htmlDependencies` and the deps used when `src = TRUE`. Feel free to re-open if you still have problems...

**Comment by h-a-graham** [comment]
Thank you Tim, I really appreciate this! I'm sure it's working great now but will confirm on Monday!

**Comment by h-a-graham** [comment]
Hi Tim, just to confirm that this did the trick and works as expected, thanks again!
