### ISSUE TITLE
Polygons Not Rendering Correctly

### ISSUE THREAD

**Issue by RayLarone** [r-spatial/leafgl#74]
I have a dataset of thousands of Car Parking Spaces I want to show on a map. However when I use the `addGlPolygons` function the polygons do not render correctly. It looks like the coordinates are not precise enough? Is there a way to increase the coordinate precision? Or some other way to resolve this issue? Many thanks

```
df <- data.frame(id = c(1, 2, 3, 4), geometry=c("POLYGON ((-0.1811010 51.52473, -0.1811554 51.52470, -0.1811693 51.52471, -0.1811150 51.52474, -0.1811010 51.52473))",
                                                "POLYGON ((-0.1811583 51.52470, -0.1812127 51.52468, -0.1812267 51.52469, -0.1811723 51.52471, -0.1811583 51.52470))",
                                                "POLYGON ((-0.1812142 51.52468, -0.1812686 51.52465, -0.1812825 51.52466, -0.1812282 51.52469, -0.1812142 51.52468))",
                                                "POLYGON ((-0.1812715 51.52465, -0.1813259 51.52462, -0.1813398 51.52463, -0.1812855 51.52466, -0.1812715 51.52465))"))

df <- df %>% st_as_sf(wkt="geometry", crs=4326)
```

## This is what is should look like:

```
df %>% st_geometry() %>% plot()
```
![Screenshot 2022-06-30 at 14 48 57](https://user-images.githubusercontent.com/87857081/176694293-e0b8aa85-a8de-40f4-939f-ecbca30fc0e4.png)

## This is how it comes out:

```
leaflet(options=leafletOptions(maxZoom = 30)) %>%
  addTiles() %>%
  addGlPolygons(data=df)
```
![Screenshot 2022-06-30 at 14 49 12](https://user-images.githubusercontent.com/87857081/176694318-76c28d30-c2bc-4048-bf88-c45de8a94fa6.png)

**Comment by trafficonese** [comment]
You should be able to use `simplify` and `digits` for `geojsonsf::sf_geojson`, but it doesn't seem to fix the problem, so I guess the bug comes from Leaflet.glify itself.

**Comment by RayLarone** [comment]
Issue is with with Leaflet.glify itself. Reposted issue on its repository: [https://github.com/robertleeplummerjr/Leaflet.glify/issues/137](https://github.com/robertleeplummerjr/Leaflet.glify/issues/137)

**Comment by tim-salabim** [comment]
https://github.com/robertleeplummerjr/Leaflet.glify/issues/137
