### ISSUE TITLE
Polygon Layer Order - pathOptions

### ISSUE THREAD

**Issue by laldew** [r-spatial/leafgl#75]
Is there a way to add ```pathOptions``` to a GlPolygons layer?  I have polygons that need to always plot on top of a polyline layer, but couldn't figure out how to do that with GlPolygons.  

For base Leaflet, I would assign the polygons to a map pane like this:  ```addPolygons(data=mydf, ... ,  options = pathOptions(pane = "myPane1") ) ```

**Comment by tim-salabim** [comment]
No, there is no `pathOptions` but `pane` can be set directly in `addGlPolygons`
